apiVersion: v1
kind: Secret
metadata:
  name: mysql-dsn
type: Opaque
stringData:
  dsn: "root:Veysel.12@tcp(mysql:3306)/haberify?parseTime=true&charset=utf8mb4"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-keys
type: Opaque
stringData:
  keys: "key1:supersecret"