apiVersion: v1
kind: ConfigMap
metadata:
  name: notes-config
data:
  APP_ENV: "prod"
  APP_PORT: "8080"
  APP_READ_TIMEOUT: "5s"
  APP_WRITE_TIMEOUT: "10s"
  DB_CONNECTION: "mysql"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_DATABASE: "go-notes"
  DB_TIMEOUT: "3s"
  MAX_BODY_BYTES: "1048576"
  CORS_ORIGINS: "http://localhost:5173,http://localhost:3000"
  METRICS_ALLOW: "0.0.0.0/0"
  BCRYPT_COST: "12"
  RATE_RPS: "10"
  RATE_BURST: "10"
  JWT_ISSUER: "go-notes-api"
  JWT_AUDIENCE: "notes-api"
  RATE_AUTH_RPS: "2"
  RATE_AUTH_BURST: "5"
  OTEL_ENDPOINT: "http://otel-collector:4318"
  OTEL_SAMPLER: "0.2"
  JTI_PREFIX: "jti:"
  REDIS_ADDR: "redis:6379"