{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "notes.fullname" . }}-ing
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
spec:
  rules:
{{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
{{- range .paths }}
          - path: {{ . | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "notes.fullname" $ }}-svc
                port: { number: {{ $.Values.service.port }} }
{{- end }}
{{- end }}
  tls:
{{ toYaml .Values.ingress.tls | nindent 4 }}
{{- end }}
