{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
type: Opaque
stringData:
{{- range $k, $v := .Values.secrets.data }}
  {{ $k }}: "{{ $v }}"
{{- end }}
{{- end }}
